export const meta = {
  name: 'bootstrap-memory',
  description: 'One-shot semantic memory generation: an Architect Agent reads the codebase and writes memory/ARCHITECTURE.md + memory/RULES.md, then a Reviewer Agent cross-checks both files against a sample of source files and corrects inaccuracies directly.',
  phases: [
    { title: 'Architect', detail: 'Read the codebase and generate memory/ARCHITECTURE.md and memory/RULES.md' },
    { title: 'Review',    detail: 'Spot-check the generated files against sampled source files and correct inaccuracies' },
    { title: 'Report',    detail: 'Summarise what was written' },
  ],
}

// ── Schemas ───────────────────────────────────────────────────────────────────

const ARCHITECT_SCHEMA = {
  type: 'object',
  properties: {
    architecture_path: { type: 'string' },
    rules_path:         { type: 'string' },
    architecture_words: { type: 'number' },
    rules_words:         { type: 'number' },
    modules_identified: { type: 'array', items: { type: 'string' } },
    summary:             { type: 'string' },
  },
  required: ['architecture_path', 'rules_path', 'architecture_words', 'rules_words', 'modules_identified', 'summary'],
}

const REVIEW_SCHEMA = {
  type: 'object',
  properties: {
    corrections_made: { type: 'array', items: { type: 'string' } },
    architecture_words: { type: 'number' },
    rules_words:         { type: 'number' },
    summary:             { type: 'string' },
  },
  required: ['corrections_made', 'architecture_words', 'rules_words', 'summary'],
}

// ── Architect ─────────────────────────────────────────────────────────────────

phase('Architect')

const architectResult = await agent(
  `You are the Architect Agent. Generate two semantic memory files for this codebase from scratch: memory/ARCHITECTURE.md and memory/RULES.md.

Use these commands/files as your primary research material:
1. Run: find . -not -path '*/.git/*' -not -path '*/node_modules/*' -type f | head -100
2. Read package.json (if it exists) for dependencies, scripts, and module type.
3. Read CLAUDE.md for repo conventions and project structure already documented by the maintainer.
4. From the file tree, identify up to 5 key entry-point files (workflow scripts, main configs, top-level READMEs, core lib files) and read them.
5. Read config files (package.json, .gitignore, settings.json, any *.config.* files) to find strict constraints (e.g. gitignore rules, required scripts, lint/format configs).

Then write memory/ARCHITECTURE.md (create the memory/ directory if it does not exist) containing, at minimum:
- Major modules/directories and what each is responsible for.
- The primary data/control flow through the system (how a request/command/spec moves through the major components).
- A list of key files with a one-line responsibility each.
- External integrations (APIs, CLIs, services, third-party tools the codebase talks to).

Also write memory/RULES.md containing, at minimum:
- Error handling patterns observed or implied by the codebase.
- Naming conventions (files, branches, commits, identifiers).
- File organization rules (where new files of each kind should go).
- Testing conventions (how/where tests live, how to run them).
- Strict constraints inferred from config files (e.g. gitignore patterns, required commit message formats, lifecycle rules).

Both files must contain substantive content — at least 200 words each, written in clear prose/markdown, not placeholder text. Use the Write tool to save both files. Base every claim on what you actually observed in the codebase; do not invent modules, files, or conventions that are not present.

Return structured output summarising what you wrote.`,
  {
    label:  'architect:bootstrap-memory',
    phase:  'Architect',
    model:  'claude-sonnet-4-6',
    schema: ARCHITECT_SCHEMA,
  },
)

if (!architectResult) {
  log('Architect agent returned no result — aborting.')
  return { status: 'failed', reason: 'architect_returned_null' }
}

log(`Architect wrote ${architectResult.architecture_words} words to ARCHITECTURE.md and ${architectResult.rules_words} words to RULES.md`)

// ── Review ────────────────────────────────────────────────────────────────────

phase('Review')

const reviewResult = await agent(
  `You are the Reviewer Agent. Your job is to fact-check and correct memory/ARCHITECTURE.md and memory/RULES.md, which were just generated by another agent from this codebase.

Steps:
1. Read memory/ARCHITECTURE.md and memory/RULES.md in full.
2. Randomly sample 5 source files from the codebase (pick files from different directories/modules where possible — use Glob/Bash find to discover candidates, then Read 5 of them).
3. Cross-check every factual claim in both memory files against what you actually observe in the sampled files and the wider repo structure (you may Read a few more files if needed to confirm or refute a claim).
4. Correct any inaccuracies directly: fix wrong file paths, wrong module descriptions, invented conventions, or outdated claims. Use the Write tool to save the corrected versions of memory/ARCHITECTURE.md and memory/RULES.md in place.
5. Preserve all content that is accurate — only change what is wrong, missing important context, or misleading. Do not shrink the files below 200 words each; if you remove inaccurate content, replace it with corrected, substantiated content instead.

Return structured output listing every correction you made (empty array if no corrections were needed) and the final word counts.`,
  {
    label:  'reviewer:bootstrap-memory',
    phase:  'Review',
    model:  'claude-haiku-4-5-20251001',
    schema: REVIEW_SCHEMA,
  },
)

if (!reviewResult) {
  log('Reviewer agent returned no result — keeping Architect output as final.')
}

// ── Report ────────────────────────────────────────────────────────────────────

phase('Report')

const finalArchWords  = reviewResult?.architecture_words ?? architectResult.architecture_words
const finalRulesWords = reviewResult?.rules_words ?? architectResult.rules_words
const corrections     = reviewResult?.corrections_made ?? []

log(`Bootstrap complete — memory/ARCHITECTURE.md (${finalArchWords} words), memory/RULES.md (${finalRulesWords} words), ${corrections.length} correction(s) applied by reviewer`)

return {
  status: 'success',
  architecture_path: 'memory/ARCHITECTURE.md',
  rules_path: 'memory/RULES.md',
  architecture_words: finalArchWords,
  rules_words: finalRulesWords,
  corrections_made: corrections,
  summary: reviewResult?.summary ?? architectResult.summary,
}
